#pragma once

#include <stdint.h>
#include <assert.h>
#include "../Libs/tlv.h"

#define DISPATCHER_IP_ADDR      2130706433 // 127.0.0.1
#define DISPATCHER_UDP_PORT     40000
#define TLV_CODE_NAME           1
#define TLV_IPC_TYPE_MSGQ       2   // TLV size 2 Bytes
#define TLV_IPC_TYPE_UXSKT      3 // TLV size 2 Bytes
#define TLV_IPC_TYPE_CBK        4
#define TLV_IPC_NET_UDP_SKT     5
#define TLV_DATA_128            6
#define TLV_DATA_256            7
#define TLV_CODE_NAME_LEN       32
#define TLV_IPC_NET_SKT_LEN     6 // 4B of IP Address, 2B of port number
#define TLV_IPC_TYPE_MSGQ_LEN   32
#define TLV_IPC_TYPE_UXSKT_LEN  32
#define TLV_IPC_TYPE_CBK_LEN    (sizeof (uintptr_t))

typedef enum ipcType_ {
    IPC_TYPE_NONE,
    IPC_TYPE_NETSKT,
    IPC_TYPE_MSGQ,
    IPC_TYPE_UXSKT,
    IPC_TYPE_SHM,
    IPC_TYPE_CBK
} ipcType_t;

typedef enum msg_type_ { 
    SUB_TO_DISPATCH,
    DISPATCH_TO_SUB,
    PUB_TO_DISPATCH,
    DISPATCH_TO_PUB
} msgType_t;

typedef enum subMsgType_ {
    SUB_MSG_DATA,   // data msg generated by publisher to be conveyed to subscriber
    SUB_MSG_ADD,    // publisher publishing a new msg or subscriber subscribing a new msg
    SUB_MSG_DELETE, // publisher unpublishing a new msg or subscriber unsubscribing a new msg
    SUB_MSG_REGISTER,
    SUB_MSG_UNREGISTER,
    SUB_MSG_ERROR,
    SUB_MSG_REQUEST_ACK,
    SUB_MSG_ACK_MSG, /* Subscriber sending back ACK*/
    SUB_MSG_SUBCRIBER_LIST, /* Publisher request COORD to tell him the subscriber List*/
    SUB_MSG_INFORM_NEW_SUBS, /* Publisher requesting COORD to tell him when new Subsc Join*/
    SUB_MSG_ID_ALLOC_SUCCESS, /* confirm the generation of Pub/Sub IDs*/
    SUB_MSG_IPC_CHANNEL_ADD, /* Add IPC Channel */
    SUB_MSG_IPC_CHANNEL_REMOVE /* Remove IPC Channel */
} subMsgType_t;

typedef enum dmsgPriority_ {
    DMSG_PR_HIGH,
    DMSG_PR_MEDIUM,
    DMSG_PR_LOW,
    DMSG_PR_MAX
} dmsgPriority_t;

typedef enum error_codes_ {
    ERROR_TLV_MISSING
} errorCodes_t;

typedef struct dmsg_ {
    /* unique ID: allocated by the dispatcher 
    If msg is generated by publisher or subscriber, the msgId will be equal to zero. Later, the dispatcher will initialize it.
    */
    uint32_t msgId;
    /*
    Direction: from publisher to the dispatcher
                from subscriber to the dispatcher
                from coordinator to subscriber
                from coordinator to publisher
    */
    msgType_t msgType;
    /*
    Register msg or unregister msg 
    simple data msg
    subscriber msg ADD
    subscriber msg DEL
    */
    subMsgType_t subMsgType;
    dmsgPriority_t priority;
    uint32_t msgCode;
    union {
        uint32_t publisherId;
        uint32_t subscriberId;
    }id;
    uint32_t refCount;
    uint16_t tlvBufferSize;
    char tlvBuffer[0];
} dmsg_t;

static inline const char *msgTypeToString(msgType_t msg_type) {
    switch (msg_type) {
        case SUB_TO_DISPATCH:
            return "SUB_TO_DISPATCH";
        case DISPATCH_TO_SUB:
            return "DISPATCH_TO_SUB";
        case PUB_TO_DISPATCH:
            return "PUB_TO_DISPATCH";
        case DISPATCH_TO_PUB:
            return "DISPATCH_TO_PUB";
    }
    return "UNKNOWN";
}

static inline const char *subMsgTypeToString(subMsgType_t sub_msg_type) {
    switch (sub_msg_type) {
        case SUB_MSG_DATA:
            return "SUB_MSG_DATA";
        case SUB_MSG_ADD:
            return "SUB_MSG_ADD";
        case SUB_MSG_DELETE:
            return "SUB_MSG_DELETE";
        case SUB_MSG_REGISTER:
            return "SUB_MSG_REGISTER";
        case SUB_MSG_UNREGISTER:
            return "SUB_MSG_UNREGISTER";
        case SUB_MSG_ERROR:
            return "SUB_MSG_ERROR";
        case SUB_MSG_ID_ALLOC_SUCCESS:
            return "SUB_MSG_ID_ALLOC_SUCCESS";
        case SUB_MSG_IPC_CHANNEL_ADD:
            return "SUB_MSG_IPC_CHANNEL_ADD";
        case SUB_MSG_IPC_CHANNEL_REMOVE:
            return "SUB_MSG_IPC_CHANNEL_REMOVE";
    }
    return "UNKNOWN";
}

static inline const char *tlvStr(int tlv_code_cpoint) {
    switch (tlv_code_cpoint) {
        case TLV_CODE_NAME:
            return "TLV_CODE_NAME";
        case TLV_IPC_TYPE_MSGQ:
            return "TLV_IPC_TYPE_MSGQ";
        case TLV_IPC_TYPE_UXSKT:
            return "TLV_IPC_TYPE_UXSKT";
        case TLV_IPC_TYPE_CBK:
            return "TLV_IPC_TYPE_CBK";
        case TLV_IPC_NET_UDP_SKT:
            return "TLV_IPC_NET_UDP_SKT";
        case TLV_DATA_128:
            return "TLV_DATA_128";
        case TLV_DATA_256:
            return "TLV_DATA_256";
    }
    return "UNKNOWN";
}

static int tlvDataLen (int tlv_code_point) {
    switch (tlv_code_point) {
        case TLV_CODE_NAME:
            return TLV_CODE_NAME_LEN; 
        case TLV_IPC_TYPE_MSGQ:
            return 64;
        case TLV_IPC_TYPE_UXSKT:
            return 64;
        case TLV_IPC_TYPE_CBK:
            return sizeof(uintptr_t);
        case TLV_IPC_NET_UDP_SKT:
            return TLV_IPC_NET_SKT_LEN;
        case TLV_DATA_128:
            return 128;
        case TLV_DATA_256:
            return 256;
    }
    return 0;
}

static inline void dmsgReference(dmsg_t *dmsg) {
    dmsg->refCount++;
}

static inline void dmsgDereference(dmsg_t *dmsg) {
    assert(dmsg->refCount);
    dmsg->refCount--;
    if(dmsg->refCount) {
        return;
    }
    free(dmsg);
}